import { Place, SouvenirItem } from '../types.js';

export const TWD_TO_KRW_RATE = 42.5; // 1 TWD ≈ 42.5 KRW

export const TAIPEI_PLACES: Record<string, Place> = {
  // --- North / Shilin / Beitou ---
  'national_palace_museum': {
    id: 'national_palace_museum',
    name: '국립고궁박물원',
    nameZh: '國立故宮博物院',
    category: 'culture',
    area: 'North',
    mrtStation: 'Shilin',
    mrtLine: 'Red',
    openTime: '09:00',
    closeTime: '17:00',
    closedDays: [1], // Closed on Mondays!
    requiresReservation: false,
    approxCostTwd: 350,
    recommendedDurationMin: 150,
    description: '세계 4대 박물관 중 하나로 70만 점에 달하는 중국 고대 유물 소장 (월요일 정기휴관)',
  },
  'shilin_night_market': {
    id: 'shilin_night_market',
    name: '스린 야시장',
    nameZh: '士林夜市',
    category: 'market',
    area: 'North',
    mrtStation: 'Jiantan',
    mrtLine: 'Red',
    openTime: '16:30',
    closeTime: '24:00',
    closedDays: [], // Open daily
    requiresReservation: false,
    approxCostTwd: 250,
    recommendedDurationMin: 120,
    description: '타이베이 최대 규모 야시장, 지파이, 왕자치즈감자, 우유튀김 등 명물 먹거리',
  },
  'beitou_hot_spring': {
    id: 'beitou_hot_spring',
    name: '신베이터우 온천/지열곡',
    nameZh: '北投溫泉 / 地熱谷',
    category: 'nature',
    area: 'North',
    mrtStation: 'Xinbeitou',
    mrtLine: 'Red (Branch)',
    openTime: '09:00',
    closeTime: '17:00',
    closedDays: [1], // Thermal Valley closed on Mondays
    requiresReservation: false,
    approxCostTwd: 150,
    recommendedDurationMin: 120,
    description: '도심 속 유황 온천 마을, 지열곡 및 온천박물관 (월요일 휴무 주의)',
  },

  // --- Suburbs / Tamsui ---
  'tamsui_old_street': {
    id: 'tamsui_old_street',
    name: '단수이 라오지에 & 위런마터우',
    nameZh: '淡水老街 / 漁人碼頭',
    category: 'attraction',
    area: 'Suburbs',
    mrtStation: 'Tamsui',
    mrtLine: 'Red',
    openTime: '10:00',
    closeTime: '21:00',
    closedDays: [],
    requiresReservation: false,
    approxCostTwd: 200,
    recommendedDurationMin: 180,
    description: '일몰 명소, 대왕카스테라, 아게이 먹거리 및 페리 승선 (타이베이 시내에서 MRT 45분 소요)',
  },
  'fort_san_domingo': {
    id: 'fort_san_domingo',
    name: '홍마오청 (단수이)',
    nameZh: '紅毛城',
    category: 'culture',
    area: 'Suburbs',
    mrtStation: 'Tamsui',
    mrtLine: 'Red',
    openTime: '09:30',
    closeTime: '17:00',
    closedDays: [1], // Often closed first Monday of each month
    requiresReservation: false,
    approxCostTwd: 80,
    recommendedDurationMin: 60,
    description: '스페인과 네덜란드 식민지 시대 요새, 영화 말할 수 없는 비밀 촬영지 근처',
  },

  // --- West / Wanhua / Ximending ---
  'ximending': {
    id: 'ximending',
    name: '시먼딩 거리',
    nameZh: '西門町',
    category: 'shopping',
    area: 'West',
    mrtStation: 'Ximen',
    mrtLine: 'Blue/Green',
    openTime: '11:00',
    closeTime: '23:00',
    closedDays: [],
    requiresReservation: false,
    approxCostTwd: 300,
    recommendedDurationMin: 120,
    description: '타이베이의 명동, 아종면선 곱창국수, 삼형매 망고빙수, 쇼핑 중심지',
  },
  'ay_chung_flour_rice_noodles': {
    id: 'ay_chung_flour_rice_noodles',
    name: '아종면선 (곱창국수)',
    nameZh: '阿宗麵線',
    category: 'restaurant',
    area: 'West',
    mrtStation: 'Ximen',
    mrtLine: 'Blue/Green',
    openTime: '09:00',
    closeTime: '22:30',
    closedDays: [],
    requiresReservation: false,
    approxCostTwd: 75,
    recommendedDurationMin: 30,
    description: '서서 먹는 가쓰오부시 육수의 쫄깃한 대만 대표 곱창국수',
  },
  'longshan_temple': {
    id: 'longshan_temple',
    name: '용산사',
    nameZh: '龍山寺',
    category: 'culture',
    area: 'West',
    mrtStation: 'Longshan Temple',
    mrtLine: 'Blue',
    openTime: '06:00',
    closeTime: '21:45',
    closedDays: [],
    requiresReservation: false,
    approxCostTwd: 0,
    recommendedDurationMin: 50,
    description: '타이베이에서 가장 오래되고 영험한 사원, 불교/도교/유교의 신들을 모심 (야경 추천)',
  },
  'bopiliao_historical_block': {
    id: 'bopiliao_historical_block',
    name: '보피랴오 역사거리',
    nameZh: '剝皮寮歷史街區',
    category: 'culture',
    area: 'West',
    mrtStation: 'Longshan Temple',
    mrtLine: 'Blue',
    openTime: '09:00',
    closeTime: '18:00',
    closedDays: [1], // Closed Mondays!
    requiresReservation: false,
    approxCostTwd: 0,
    recommendedDurationMin: 50,
    description: '청나라와 일제강점기 붉은 벽돌 건물이 보존된 레트로 감성 문화거리',
  },

  // --- Center / Zhongshan / Da’an / Zhongzheng ---
  'fuhang_soy_milk': {
    id: 'fuhang_soy_milk',
    name: '푸항또우장 (화산시장)',
    nameZh: '阜杭豆漿',
    category: 'restaurant',
    area: 'Center',
    mrtStation: 'Shandao Temple',
    mrtLine: 'Blue',
    openTime: '05:30',
    closeTime: '12:30', // Morning only!
    closedDays: [1], // Strictly closed on Mondays!
    requiresReservation: false,
    approxCostTwd: 100,
    recommendedDurationMin: 60,
    description: '미슐랭 빕구르망 대만식 아침식사(또우장 & 요우티아오), 아침 일찍 웨이팅 필수 (월요일 휴무)',
  },
  'chiang_kai_shek_memorial': {
    id: 'chiang_kai_shek_memorial',
    name: '중정기념당',
    nameZh: '中正紀念堂',
    category: 'culture',
    area: 'Center',
    mrtStation: 'Chiang Kai-shek Memorial Hall',
    mrtLine: 'Red/Green',
    openTime: '09:00',
    closeTime: '18:00',
    closedDays: [],
    requiresReservation: false,
    approxCostTwd: 0,
    recommendedDurationMin: 70,
    description: '대만 초대 총통 장제스를 기리는 기념관, 매 정시 근위병 교대식 진행',
  },
  'yongkang_street': {
    id: 'yongkang_street',
    name: '융캉제 미식거리',
    nameZh: '永康街',
    category: 'shopping',
    area: 'Center',
    mrtStation: 'Dongmen',
    mrtLine: 'Red/Orange',
    openTime: '10:00',
    closeTime: '21:30',
    closedDays: [],
    requiresReservation: false,
    approxCostTwd: 350,
    recommendedDurationMin: 90,
    description: '딘타이펑 본점, 총좌빙, 스무시 망고빙수, 예쁜 티 샵과 소품샵이 모여 있는 감성 거리',
  },
  'din_tai_fung_xinyi': {
    id: 'din_tai_fung_xinyi',
    name: '딘타이펑 (신성점/융캉)',
    nameZh: '鼎泰豐 新生店',
    category: 'restaurant',
    area: 'Center',
    mrtStation: 'Dongmen',
    mrtLine: 'Red/Orange',
    openTime: '10:30',
    closeTime: '20:30',
    closedDays: [],
    requiresReservation: false, // 앱 대기표 등록
    approxCostTwd: 500,
    recommendedDurationMin: 75,
    description: '세계적인 딤섬 전문점, 샤오롱바오, 갈비튀김 볶음밥 필수 주문 (웨이팅 고려 필요)',
  },
  'huashan_1914': {
    id: 'huashan_1914',
    name: '화산 1914 창의문화원구',
    nameZh: '華山1914文化創意產業園區',
    category: 'culture',
    area: 'Center',
    mrtStation: 'Zhongxiao Xinsheng',
    mrtLine: 'Blue/Orange',
    openTime: '09:30',
    closeTime: '21:00',
    closedDays: [],
    requiresReservation: false,
    approxCostTwd: 150,
    recommendedDurationMin: 90,
    description: '과거 양조장을 개조한 복합 문화 예술 단지, 전시회 및 독립 디자이너 굿즈 숍',
  },
  'kiki_restaurant': {
    id: 'kiki_restaurant',
    name: '키키 레스토랑 (사천요리)',
    nameZh: 'KiKi 餐廳',
    category: 'restaurant',
    area: 'East',
    mrtStation: 'Sun Yat-sen Memorial Hall',
    mrtLine: 'Blue',
    openTime: '11:30',
    closeTime: '22:00',
    breakTimeStart: '15:00', // Break time!
    breakTimeEnd: '17:15', // Reopens at 17:15
    closedDays: [],
    requiresReservation: true,
    approxCostTwd: 550,
    recommendedDurationMin: 75,
    description: '연두부 튀김(노호두부), 부추꽃볶음으로 한국인에게 인기 높은 사천요리 (브레이크타임 15~17시)',
  },

  // --- East / Xinyi / Songshan ---
  'taipei_101': {
    id: 'taipei_101',
    name: '타이베이 101 전망대 & 쇼핑몰',
    nameZh: '台北101觀景台',
    category: 'attraction',
    area: 'East',
    mrtStation: 'Taipei 101/World Trade Center',
    mrtLine: 'Red',
    openTime: '10:00',
    closeTime: '21:00',
    closedDays: [],
    requiresReservation: false, // 사전 예매 권장
    approxCostTwd: 600,
    recommendedDurationMin: 90,
    description: '타이베이의 랜드마크 초고층 빌딩, 89층 실내 전망대 및 윈드 댐퍼 관람',
  },
  'xiangshan_trail': {
    id: 'xiangshan_trail',
    name: '샹산 (코끼리산) 전망대',
    nameZh: '象山步道',
    category: 'nature',
    area: 'East',
    mrtStation: 'Xiangshan',
    mrtLine: 'Red',
    openTime: '00:00',
    closeTime: '24:00',
    closedDays: [],
    requiresReservation: false,
    approxCostTwd: 0,
    recommendedDurationMin: 70,
    description: '타이베이 101과 도시 전경이 한눈에 보이는 일몰/야경 트레킹 명소 (계단 약 20분 소요)',
  },
  'raohe_night_market': {
    id: 'raohe_night_market',
    name: '라오허제 야시장',
    nameZh: '饒河街觀光夜市',
    category: 'market',
    area: 'East',
    mrtStation: 'Songshan',
    mrtLine: 'Green',
    openTime: '17:00',
    closeTime: '23:30',
    closedDays: [],
    requiresReservation: false,
    approxCostTwd: 250,
    recommendedDurationMin: 90,
    description: '자우궁 사원 입구 옆 위치, 화덕만두(후자오빙), 소시지, 과일 등 미식 특화 야시장',
  },
  'songshan_cultural_park': {
    id: 'songshan_cultural_park',
    name: '송산문창원구 & 성품서점',
    nameZh: '松山文創園區',
    category: 'culture',
    area: 'East',
    mrtStation: 'Taipei City Hall',
    mrtLine: 'Blue',
    openTime: '09:00',
    closeTime: '18:00',
    closedDays: [],
    requiresReservation: false,
    approxCostTwd: 100,
    recommendedDurationMin: 80,
    description: '옛 담배공장을 리모델링한 문화예술 지구 및 대만 감성 서점 성품서점',
  },

  // --- Transport Hubs ---
  'taipei_main_station': {
    id: 'taipei_main_station',
    name: '타이베이 메인 스테이션 (교통 중심)',
    nameZh: '台北車站',
    category: 'transport',
    area: 'Center',
    mrtStation: 'Taipei Main Station',
    mrtLine: 'Red/Blue/Airport MRT',
    openTime: '06:00',
    closeTime: '24:00',
    closedDays: [],
    requiresReservation: false,
    approxCostTwd: 50,
    recommendedDurationMin: 30,
    description: '공항철도, 고속철도(HSR), MRT 레드/블루 라인이 교차하는 대중교통의 심장부',
  },
  'taoyuan_airport': {
    id: 'taoyuan_airport',
    name: '타오위안 국제공항 (TPE)',
    nameZh: '臺灣桃園國際機場',
    category: 'transport',
    area: 'Suburbs',
    mrtStation: 'Airport Terminal 1 / 2',
    mrtLine: 'Airport MRT',
    openTime: '00:00',
    closeTime: '24:00',
    closedDays: [],
    requiresReservation: false,
    approxCostTwd: 160,
    recommendedDurationMin: 60,
    description: '타이베이 주요 국제공항, 익스프레스 공항철도로 타이베이 메인역까지 약 36분',
  },
  'coffee_show_nangang': {
    id: 'coffee_show_nangang',
    name: '2026 대만 국제 커피쇼 (난강전람관 1관)',
    nameZh: '2026 台灣國際咖啡展 (南港展覽館 1館)',
    category: 'attraction',
    area: 'East',
    mrtStation: 'Taipei Nangang Exhibition Center',
    mrtLine: 'Blue/Brown',
    openTime: '10:00',
    closeTime: '18:00',
    closedDays: [],
    requiresReservation: false,
    approxCostTwd: 0, // 사전등록 시 무료입장
    recommendedDurationMin: 240,
    description: '11/13~16 개최 아시아 최대 커피 축제, 세계 챔피언 바리스타 시연, 글로벌 게이샤 생두 커핑 및 에스프레소 장비 박람회',
  },
  'simple_kaffa_huashan': {
    id: 'simple_kaffa_huashan',
    name: '심플 카파 본점 (Simple Kaffa 興波咖啡)',
    nameZh: '興波咖啡 旗艦店',
    category: 'cafe',
    area: 'Center',
    mrtStation: 'Zhongxiao Xinsheng',
    mrtLine: 'Blue/Orange',
    openTime: '10:00',
    closeTime: '17:00',
    closedDays: [],
    requiresReservation: false,
    approxCostTwd: 250,
    recommendedDurationMin: 60,
    description: '2016 월드 바리스타 챔피언 Berg Wu의 플래그십 매장, 스페셜티 커피 애호가들의 필수 순례지',
  },
  'liu_shan_dong': {
    id: 'liu_shan_dong',
    name: '유산동 우육면 (劉山東牛肉麵)',
    nameZh: '劉山東牛肉麵',
    category: 'restaurant',
    area: 'West',
    mrtStation: 'Taipei Main Station',
    mrtLine: 'Red/Blue',
    openTime: '08:00',
    closeTime: '20:00',
    closedDays: [0], // Closed Sundays
    requiresReservation: false,
    approxCostTwd: 220,
    recommendedDurationMin: 45,
    description: '미슐랭 빕구르망 선정, 70년 전통의 깊고 맑은 칭둔 우육면과 진한 홍샤오 우육면',
  },
  'jin_feng_luroufan': {
    id: 'jin_feng_luroufan',
    name: '진펑루로우판 (金峰魯肉飯)',
    nameZh: '金峰魯肉飯',
    category: 'restaurant',
    area: 'Center',
    mrtStation: 'Chiang Kai-shek Memorial Hall',
    mrtLine: 'Red/Green',
    openTime: '09:00',
    closeTime: '23:30',
    closedDays: [],
    requiresReservation: false,
    approxCostTwd: 120,
    recommendedDurationMin: 40,
    description: '미슐랭 빕구르망 선정, 부드러운 간장 조림 돼지고기 덮밥(루로우판)과 계란 장조림',
  },
  'dihua_street': {
    id: 'dihua_street',
    name: '디화제 레트로 상점가 & 다다오청',
    nameZh: '迪化街 / 大稻埕',
    category: 'shopping',
    area: 'West',
    mrtStation: 'Beimen',
    mrtLine: 'Green',
    openTime: '09:30',
    closeTime: '19:00',
    closedDays: [],
    requiresReservation: false,
    approxCostTwd: 300,
    recommendedDurationMin: 90,
    description: '100년 역사의 붉은 벽돌 상점가, 부부 화목을 기원하는 하해성황묘 및 기념품·차 쇼핑',
  },
  'hotel_gracery_taipei': {
    id: 'hotel_gracery_taipei',
    name: '호텔 그레이스리 타이베이 (중샤오신생)',
    nameZh: '格拉斯麗台北飯店',
    category: 'attraction',
    area: 'Center',
    mrtStation: 'Zhongxiao Xinsheng',
    mrtLine: 'Blue/Orange',
    openTime: '00:00',
    closeTime: '24:00',
    closedDays: [],
    requiresReservation: true,
    approxCostTwd: 0,
    recommendedDurationMin: 30,
    description: '중샤오신생역 도보 1분, 블루라인 커피쇼 난강전람관 직통 16분, 스탠다드 트윈룸 완비',
  }
};

/**
 * Transit matrix between areas in Taipei in minutes
 */
export const AREA_TRANSIT_ESTIMATES: Record<string, Record<string, { min: number; cost: number; mrtLine: string }>> = {
  Center: {
    Center: { min: 10, cost: 20, mrtLine: 'Walk/MRT' },
    West: { min: 12, cost: 20, mrtLine: 'Blue Line' },
    East: { min: 15, cost: 25, mrtLine: 'Red/Blue Line' },
    North: { min: 25, cost: 30, mrtLine: 'Red Line' },
    Suburbs: { min: 45, cost: 50, mrtLine: 'Red Line (Tamsui)' },
  },
  West: {
    Center: { min: 12, cost: 20, mrtLine: 'Blue Line' },
    West: { min: 10, cost: 20, mrtLine: 'Walk/MRT' },
    East: { min: 20, cost: 25, mrtLine: 'Blue Line' },
    North: { min: 25, cost: 30, mrtLine: 'Green/Red Line' },
    Suburbs: { min: 50, cost: 55, mrtLine: 'MRT Transfer' },
  },
  East: {
    Center: { min: 15, cost: 25, mrtLine: 'Red/Blue Line' },
    West: { min: 20, cost: 25, mrtLine: 'Blue Line' },
    East: { min: 10, cost: 20, mrtLine: 'Walk/MRT' },
    North: { min: 30, cost: 35, mrtLine: 'Red Line' },
    Suburbs: { min: 55, cost: 60, mrtLine: 'MRT Red Line' },
  },
  North: {
    Center: { min: 25, cost: 30, mrtLine: 'Red Line' },
    West: { min: 25, cost: 30, mrtLine: 'Red/Green Line' },
    East: { min: 30, cost: 35, mrtLine: 'Red Line' },
    North: { min: 12, cost: 20, mrtLine: 'Red Line' },
    Suburbs: { min: 25, cost: 30, mrtLine: 'Red Line to Tamsui' },
  },
  Suburbs: {
    Center: { min: 45, cost: 50, mrtLine: 'Red Line' },
    West: { min: 50, cost: 55, mrtLine: 'Red/Blue Line' },
    East: { min: 55, cost: 60, mrtLine: 'Red Line' },
    North: { min: 25, cost: 30, mrtLine: 'Red Line' },
    Suburbs: { min: 15, cost: 25, mrtLine: 'Bus/Ferry' },
  },
};

/**
 * Curated Souvenirs Database (3 distinct tiers)
 */
export const TAIPEI_SOUVENIRS: SouvenirItem[] = [
  // Tier 1: 꼭 살만한 아이템 (본인 취향: 커피/위스키/명품차 + 대중적 인기)
  {
    category: 'must_buy',
    categoryLabel: '대만 필수 추천템 (취향·대중적 명품)',
    name: '카발란 솔리스트 싱글몰트 위스키 (Kavalan Solist)',
    nameZh: '噶瑪蘭 經典獨奏 原酒威士忌',
    targetRecipient: '나 & 가족 (위스키 애호가)',
    priceKrw: '약 12만 ~ 18만 원',
    priceTwd: '2,800 ~ 4,200 TWD',
    purchaseLocation: '타이베이 시내 카발란 플래그십 숍 or 타오위안 공항 면세점',
    description: '세계 유수의 위스키 어워드를 휩쓴 대만 대표 싱글 캐스크 스트렝스(CS) 위스키. 비노바리끄(Vinho Barrique) 또는 올로로소 셰리(Oloroso Sherry) 캐스크가 최고 인기.',
    tips: '한국 주류세 감안 시 대만 현지 면세점 구입 시 국내 가격의 절반 이하로 극상의 가성비.'
  },
  {
    category: 'must_buy',
    categoryLabel: '대만 필수 추천템 (취향·대중적 명품)',
    name: '대만 스페셜티 커피 원두 & 드립백 (심플 카파 / 난강 커피쇼 한정)',
    nameZh: '興波咖啡 冠軍精品咖啡豆',
    targetRecipient: '나 (스페셜티 커피 취향)',
    priceKrw: '약 2만 ~ 5만 원',
    priceTwd: '500 ~ 1,200 TWD',
    purchaseLocation: '11/13 난강 국제 커피쇼 전시장 부스 or 심플 카파(Simple Kaffa) 플래그십 매장',
    description: '2016 월드 바리스타 챔피언 Berg Wu의 시그니처 블렌드 및 11/13 커피쇼 전시장 현장에서만 구매 가능한 파나마 게이샤 / 대만 아리산 고산 커피 생두 로스팅 원두.',
    tips: '커피쇼 현장 부스에서 특별 할인 및 현장 테이스팅 후 취향에 맞는 원두 선택 가능.'
  },
  {
    category: 'must_buy',
    categoryLabel: '대만 필수 추천템 (취향·대중적 명품)',
    name: '금문고량주 58도 (Kinmen Kaoliang Liquor)',
    nameZh: '金門高粱酒 58度',
    targetRecipient: '애주가 및 소장용',
    priceKrw: '약 2만 ~ 3만 원',
    priceTwd: '500 ~ 650 TWD',
    purchaseLocation: '까르푸(Carrefour), 편의점 또는 면세점',
    description: '대만 진먼도에서 생산되는 수수 증류 백주. 숙취가 없고 향긋한 곡물향이 일품인 대만 국민 명주.',
    tips: '보급형 흰 라벨(백룡) 58도가 가장 가성비가 좋으며, 기념용 블랙 라벨 프리미엄도 추천.'
  },

  // Tier 2: 부모님 선물 아이템 (고급/건강/전통)
  {
    category: 'parents',
    categoryLabel: '부모님 효도 선물 (건강·프리미엄 차)',
    name: '대만 고산 우롱차 & 동정 우롱차 프리미엄 세트',
    nameZh: '阿里山高山烏龍茶 / 凍頂烏龍茶 禮盒',
    targetRecipient: '양가 부모님',
    priceKrw: '약 5만 ~ 15만 원',
    priceTwd: '1,200 ~ 3,500 TWD',
    purchaseLocation: '디화제(迪化街) 100년 전통 찻집(임화태다행 등) or 성품서점 티 숍',
    description: '해발 1,000m 이상 고지대에서 손으로 딴 프리미엄 찻잎. 깊은 꽃향과 부드러운 단맛이 일품이며 고급스러운 철제 틴케이스 포장 제공.',
    tips: '디화제 노포 다원에서는 시음 후 원하는 등급과 향(청향/농향)을 직접 골라 포장 가능.'
  },
  {
    category: 'parents',
    categoryLabel: '부모님 효도 선물 (건강·프리미엄 차)',
    name: '금문도 일조조(一條根) 한방 파스 & 온열 크림',
    nameZh: '金門一條根 精油貼布 / 萬應膏',
    targetRecipient: '부모님 (관절·근육 건강)',
    priceKrw: '약 1만 ~ 2만 원 (팩당)',
    priceTwd: '250 ~ 450 TWD',
    purchaseLocation: '코스메드(Cosmed), 왓슨스(Watsons) 또는 현지 대형 약국',
    description: '대만 금문도 특산 한방 식물인 ‘일조조’ 성분 파스. 뻐근한 무릎, 어깨, 허리에 탁월한 온열/쿨링 진통 효과로 어르신 선물 만족도 1위.',
    tips: '금문도(金門) 정품 로고 홀로그램이 붙은 대형 팩(7~10매입)을 3~5개 묶음 구매 추천.'
  },
  {
    category: 'parents',
    categoryLabel: '부모님 효도 선물 (건강·프리미엄 차)',
    name: '써니힐 (SunnyHills) 100% 토종 파인애플 펑리수',
    nameZh: '微熱山丘 土鳳梨酥',
    targetRecipient: '부모님 및 어르신',
    priceKrw: '약 2만 ~ 3만 5천 원',
    priceTwd: '500 ~ 800 TWD',
    purchaseLocation: '타오위안 공항 T1 면세구역 or 신광미츠코시 백화점',
    description: '동과(박)나 설탕 범벅이 아닌 100% 진짜 파인애플 과육과 에쉬레 천연 버터를 사용해 묵직한 과육과 고급스러운 풍미를 자랑하는 하이엔드 펑리수.',
    tips: '고급 에코백에 담아주어 선물 전달 시 격식과 정성이 돋보임.'
  },
  {
    category: 'parents',
    categoryLabel: '부모님 효도 선물 (건강·프리미엄 차)',
    name: '디화제 리르청(李日勝) 자연산 야생 어란 (보타르고, 烏魚子)',
    nameZh: '迪化街 李日勝 野生烏魚子',
    targetRecipient: '부모님 특별 미식 선물',
    priceKrw: '약 4만 ~ 8만 원',
    priceTwd: '1,000 ~ 2,000 TWD',
    purchaseLocation: '디화제(迪化街) 리르청 본점',
    description: '대만 겨울철 진미인 숭어알(보타르고). 살짝 구워 사과나 대파와 곁들이면 고급 안주 및 밥도둑으로 부모님 세대에게 인기 만점.',
    tips: '진공포장되어 상온 1~2주, 냉동 시 수개월 보관 가능하여 비행기 반입 용이.'
  },

  // Tier 3: 회사 동료용 나눔 간식 (개당 5천원 내외 / ~120 TWD)
  {
    category: 'colleagues',
    categoryLabel: '회사 동료 나눔용 (개당 5천원 내외)',
    name: '세인트피터 (Saint Peter) 커피·초코 누가크래커',
    nameZh: '聖比德 咖啡牛軋餅',
    targetRecipient: '회사 팀원 & 부서 동료',
    priceKrw: '개당 약 6,000원 (상자당 ~150 TWD, 30개입)',
    priceTwd: '150 ~ 180 TWD / 상자',
    purchaseLocation: '동먼역(융캉제) 세인트피터 본점 or 시먼딩 지점',
    description: '한 입 크기의 앙증맞은 사이즈에 진한 커피향/초코향 누가가 들어간 크래커. 1상자에 30개 개별 포장되어 있어 1~2상자만 사도 팀원 전원에게 2~3개씩 돌리기 압도적 1위.',
    tips: '전자레인지에 5초만 살짝 돌려 먹으면 누가가 부드럽게 녹아 커피와 환상적인 궁합.'
  },
  {
    category: 'colleagues',
    categoryLabel: '회사 동료 나눔용 (개당 5천원 내외)',
    name: '닥터큐 (Dr. Q) 곤약젤리 (망고/리치/패션후르츠)',
    nameZh: 'Dr. Q 蒟蒻果凍',
    targetRecipient: '회사 동료 및 다인원',
    priceKrw: '봉지당 약 2,000 ~ 2,500원',
    priceTwd: '45 ~ 55 TWD / 봉지',
    purchaseLocation: '까르푸(Carrefour), PX마트, 편의점',
    description: '진짜 과즙이 듬뿍 들어간 튜브형 곤약젤리. 국물이 흐르지 않는 안심 커팅 구조로 사무실 서랍에 두고 먹기 좋아 회사 동료들에게 2~3개씩 뿌리기 최고.',
    tips: '부피와 무게 부담이 적어 4~5봉지 사면 부서 전체에 가성비 있게 나눔 가능.'
  },
  {
    category: 'colleagues',
    categoryLabel: '회사 동료 나눔용 (개당 5천원 내외)',
    name: '유키앤러브 (Yuki & Love) 망고젤리',
    nameZh: '雪之戀 芒果凍',
    targetRecipient: '회사 친한 동료',
    priceKrw: '상자당 약 3,500 ~ 4,500원',
    priceTwd: '80 ~ 100 TWD / 상자',
    purchaseLocation: '디화제 상점가, 까르푸, 야시장 기념품점',
    description: '대만 망고 과즙 듬뿍, 탱글탱글하고 시원한 망고 젤리. 1박스에 10개입으로 개별 포장되어 있어 1인당 1상자씩 부담 없이 선물하기 적합.',
    tips: '냉동실에 얼려 먹으면 천연 샤베트처럼 더욱 맛있음.'
  },
  {
    category: 'colleagues',
    categoryLabel: '회사 동료 나눔용 (개당 5천원 내외)',
    name: '3시 15분 (3:15pm) 대만 오리지널 밀크티 티백',
    nameZh: '三點一刻 原味奶茶',
    targetRecipient: '사무실 동료',
    priceKrw: '봉지당 약 5,000원 (15개입 팩)',
    priceTwd: '120 TWD / 대용량 팩',
    purchaseLocation: '까르푸, 드럭스토어, 대형마트',
    description: '가루가 아닌 진짜 홍차 잎이 든 티백 형태로 물에 우려내는 원조 대만 밀크티. 낱개 티백을 회사 탕비실에 두거나 동료 책상 위에 하나씩 올려놓기 좋음.',
    tips: '오리지널(Original)과 로스트(Roasted) 맛이 가장 대중적으로 인기.'
  },
  {
    category: 'colleagues',
    categoryLabel: '회사 동료 나눔용 (개당 5천원 내외)',
    name: '만한대찬 (滿漢大餐) 프리미엄 우육면 라면',
    nameZh: '滿漢大餐 牛肉麵',
    targetRecipient: '친한 직속 팀원 / 동기',
    priceKrw: '개당 약 2,300 ~ 2,800원',
    priceTwd: '55 ~ 65 TWD / 컵',
    purchaseLocation: '편의점(7-Eleven, FamilyMart) or 까르푸',
    description: '진짜 큼직한 소고기 덩어리 레토르트 파우치가 통째로 들어있는 대만 명물 프리미엄 우육면.',
    tips: '보라색(진한 매운맛, 麻辣鍋牛肉麵)과 파란색(진국 소고기맛, 蔥燒牛肉麵)이 인기 투톱.'
  }
];

